package mbtinder.lib.constant

enum class ServerResponse {
    USER_ID_NOT_FOUND,
    USER_NOT_FOUND,
    EMAIL_NOT_FOUND,
    EMAIL_DUPLICATED,
    PASSWORD_MISMATCH,
    CHAT_ID_NOT_FOUND,
    IMAGE_NOT_FOUND,
    IMAGE_ID_NOT_FOUND,
    ANSWERED_QUESTION
}